version: "3.9"
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: 123
      POSTGRES_USER: postgres
      POSTGRES_DB: qadb
    ports:
      - "3001:5432"
  web:
    image: jackzhen1996/node-server:latest
    depends_on:
      - db
    ports:
      - "3000:3000"


